name: flutter_myproject_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  audioplayers: ^6.2.0
  cloud_firestore: ^5.6.4
  curved_labeled_navigation_bar: ^2.0.6
  firebase_core: ^3.12.0
  path_provider: ^2.0.1
  flutter:
    sdk: flutter
  lite_rolling_switch: ^1.0.1
  video_player: ^2.3.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_bloc: ^8.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/video/ss1.mp4
  fonts:
    - family: Sunflare
      fonts:
        - asset: assets/fonts/Sunflare.ttf
